[package]
name = "rofishy/network"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.17.0"
Promise = "evaera/promise@4.0.0"